### ISSUE TITLE
Leaving pages unstructured needs always a retry of the moving action in the structure tree

### ISSUE THREAD

**Issue by subhhwendt** [kitodo/kitodo-production#3476]
Step 1
![grafik](https://user-images.githubusercontent.com/5708995/79567527-accff580-80b4-11ea-8c61-3990e49671bf.png)
 
Result makes unhappy regarding page numbering….. 
![grafik](https://user-images.githubusercontent.com/5708995/79567574-c3764c80-80b4-11ea-9c89-7e5828486e99.png)

Step 2: You can correct in the structure tree! 
First try fails
 
![grafik](https://user-images.githubusercontent.com/5708995/79567616-d5f08600-80b4-11ea-8c93-04b36f5a02c3.png)

Second try is ok - and it remains ok after saving the process
![grafik](https://user-images.githubusercontent.com/5708995/79567649-e43ea200-80b4-11ea-90a6-4ff6db0b014f.png)

**Comment by solth** [comment]
> Result makes unhappy regarding page numbering…..

Thanks for the very specific and useful problem description :stuck_out_tongue_closed_eyes:

If I understand you correctly, the missing option `Create element here` (or something like that, e.g. "at the same place of the selected pages") is what makes you unhappy, right? If there is not already feature request ticket for this, we should add it.

Given the current - probably insufficient - options to add new elements at specific locations, the re-numbering of the pages assigned to the newly created structural element seems correct though. Since the `Titelblatt` was added as the _first_ _child_ of the `Monographie`, it was inserted _before_ original pages 1 and 2 and all pages were re-numbered accordingly.

The actual bug in this issue seems to be the two tries required to succesfully move the created structural element. Is that correct?

**Comment by subhhwendt** [comment]
Sorry for my next mismatch in writing tickets -I tried to fulfill your requirement for a complete view for a problem. 
I confirm that the actual bug refer to the two tries required for the intended move.

**Comment by matthias-ronge** [comment]
It looks like this is partly the problem described in #4038. @subhhwendt, what is shown in the structure tree, is not the pagination, but an internal command number. That is confusing. That's what I described in the other ticket. (In your example, the _pagination_ is "` - `" for all images).

A second (and independent) problem, if I understand correctly, is that the newly created division appears just below the parent node, and the unassigned images with a smaller number after it; they should appear before it. There shouldn't be a new function for this, it should always happen that way.

**Wrong:** (the numbers here indicate the image number, assuming #4038 is fixed)
```
📁 Monograph
   📁 Title page
      🖼️ 4
      🖼️ 3
   🖼️ 1
   🖼️ 2
   🖼️ 5
   🖼️ 6
   …
```

**Correct:**
```
📁 Monograph
   🖼️ 1
   🖼️ 2
   📁 Title page
      🖼️ 4
      🖼️ 3
   🖼️ 5
   🖼️ 6
   …
```

Goal: I would suggest focusing this ticket on the second problem and solving the numbering display problem with the other ticket.

**Comment by solth** [comment]
@subhhwendt Can you confirm that the actual bug reported in this issue - e.g. two drag'n'drop actions are required to move a new structure element - still occurs? I just tested this with the current master and the structure element - including its assigned pages - was successfully moved on the first try.

**Comment by subhhwendt** [comment]
I confirm - there's no bug!!
